spring:
  application:
    name: webflux-practice

  webflux:
    base-path: /webflux

  datasource:
    url: jdbc:postgresql://localhost:5434/webflux
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: classpath:gatewayRule.yml

server:
  port: 1234

logging:
  level:
    root: INFO
    org.springframework.web.server: TRACE
