logging:
  level:
    root: INFO
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
#    org.springframework.cloud.gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://localhost:1234/
          predicates:
            - Path=/webflux/api/test
          filters:
            - RewritePath=/webflux/api/test, /webflux/redirect
            - name: AddBasicAuth
              args:
                username: admin
                password: admin888


#      routes:
#        - id: test_route
#          uri: http://localhost:1234/
#          predicates:
#          - Path=/webflux/api/test
#          filters:
#          - RewritePath=/webflux/api/test, /webflux/api/redirect
#          - username: asd